### ISSUE TITLE
Pattern from SVG / Creating stitch-covered areas inside closed Polylines

### ISSUE THREAD

**Issue by seghier** [fstwn/pyembroideryGH#1]
Hello
thank you so much for this and i hope you open a thread in Rhino forum about it
i see your example , can the addon digitize svg or create embroidery from any shape?

**Comment by fstwn** [comment]
Thank you, I haven't made a post but maybe will do so.

Unfortunately, the capabilities are still a little limited. Think of it like this: You can create stitches from any Polyline in Rhino/GH. So if you have a svg line graphic, you can import it into rhino and then embroider along those lines for example.
What's missing up until now is functionality for making "areas" of stitches. So you can't cover a coloured area in the svg with stitches automatically (yet).

I will try to add that functionality in the coming weeks/months as I'll be working on an update for the next semester.

I hope I could answer your question :)

**Comment by seghier** [comment]
thank you 
few days ago i used another tool to convert dst file to gcode than i find python module which don't work with grasshopper
i tried to make area of stitch with zigzag curve but i don't know how to convert points and lines.
i searched alot since days but i never found your addon until today when i ask the developer of pyembroidery,
that why i asked you to share you addon in the forum and food4rhino, many people will use it for sure.
i will try it more because before i used native components and a little python to extract some informations.
thank you again , i wait your update

**Comment by fstwn** [comment]
If you can share some screenshots of what you are trying to do, I might be able to shoot out a quick example.

If I got it correct, you try to import and modify a dst file? At least loading that should be possible without an update. You can also send me the dst so I can have a look at it.

Always happy to help :)

**Comment by seghier** [comment]
Thank you , this is the dst file

https://www.dropbox.com/s/h1i2t12zu8g2i1e/test%20new.DST?dl=0

i test your addon and it work excellent, i add a random input to pattern stitch block to change colors.
you can see the what i did before finding your addon in this thread.
https://discourse.mcneel.com/t/embroidery-with-grasshopper/106841/7
and this is a screenshot of the same animation with your addon

![image](https://user-images.githubusercontent.com/6026588/90105066-8e69c600-dd45-11ea-9736-abffc7611701.png)

**Comment by fstwn** [comment]
So cool to see that people are actually using this!! Thank you for your feedback, will have a look into it as soon as possible.

Also got some inspiration about handling the punching of coloured areas inside of gh from your g-code animations. Very cool! :)

The original idea was to bypass conventional software for creating embroidery patterns and to do everything directly in gh. So maybe in the not too distant future this will be possible :)

Your "simulation animation" for the embroidery is also great! Maybe it could be useful to incorporate such a simulation also into the add-on. If you're interested to collaborate on this, hit me up. Otherwise I'd probably have a try myself if you don't mind.

Best, Max

**Comment by seghier** [comment]
Thank you very much 👍 
yes of course i will send you the old and the new scripts to see the idea maybe you can make it easier with python
also about the animation the original code have Z with value so maybe it is easy to extract them directly as z values for the needle with values -z to +z, and the extracted y must be always -y.
there are also stop and change color command which are useful to animate needle like in reality but it's hard to do that by components.
i will also try to create new icons for your components if you have ideas just draw them or show me similar icons from embroidery software
many thanks again , great addon :)

**Comment by seghier** [comment]
Two gh definitions

https://www.dropbox.com/s/wik9rycdzix5em0/embroidery%20with%20addon.gh?dl=0

https://www.dropbox.com/s/o74by6ueplu8ote/needle%20anim.gh?dl=0

**Comment by seghier** [comment]
This is a different approach to switch between animation, simply change x,y to (-x,y) (x,-y)
https://www.dropbox.com/s/2r8nhgvqubfzd0p/switch%20needle%20animation.gh?dl=0

![image](https://user-images.githubusercontent.com/6026588/90169583-13cd9480-dd9f-11ea-8a36-048ee16d3e54.png)

**Comment by fstwn** [comment]
Hey, just to let you know: Will have a look at this over the next days, starting today.
As far as I can tell right now, I'll probably re-write large bits of all components, as the item/list/tree access is pretty messed up on most of them (doing it "manually" in a lot of places where it should not be necessary).

**Comment by seghier** [comment]
thank you i wait for it
